server:
  port: 8081

spring:
  application:
    name: order-shipping-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queues:
  stockCheck: orders.stock-check
  shippingCheck: orders.shipping-check
  payment: orders.payment
  paymentSuccess: payments.success
  paymentFailed: payments.failed
  errorLogs: logs.error
  inventoryRelease: inventory.release.queue
  shippingRelease: shipping.release.queue

exchanges:
  orders: orders
  payments: payments
  shipping: shipping
  logs: logs

bindings:
  stockCheck:
    queue: orders.stock-check
    exchange: orders
    routingKey: stock.check
  shippingCheck:
    queue: orders.shipping-check
    exchange: orders
    routingKey: shipping.check
  payment:
    queue: orders.payment
    exchange: orders
    routingKey: order.paid
  paymentSuccess:
    queue: payments.success
    exchange: payments
    routingKey: payment.success
  paymentFailed:
    queue: payments.failed
    exchange: payments
    routingKey: payment.failed
  errorLogs:
    queue: logs.error
    exchange: logs
    routingKey: "#.Error"
  inventoryRelease:
    queue: inventory.release.queue
    exchange: orders
    routingKey: inventory.release
  shippingRelease:
    queue: shipping.release.queue
    exchange: orders
    routingKey: shipping.release

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/